apiVersion: v1
kind: Service
metadata:
  labels:
    run: produtos-ms-mongo
  name: produtos-ms-mongo
  namespace: totem
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 27017
      nodePort: 32438
  selector:
    app: produtos-ms-mongo