apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: produtos-ms-mongo
  namespace: totem
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
