apiVersion: v1
kind: Service
metadata:
  labels:
    run: produtos-ms
  name: produtos-ms
  namespace: produtos-ms
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 31000
  selector:
    app: produtos-ms