apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtos-ms-mongo
  namespace: totem
  labels:
    app: produtos-ms-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtos-ms-mongo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: produtos-ms-mongo
    spec:
      volumes:
      - name: produtos-ms-mongo
        persistentVolumeClaim:
          claimName: produtos-ms-mongo
      containers:
      - name: produtos-ms-mongo
        envFrom:
        - configMapRef:
            name: produtos-ms-configmap
        - secretRef:
            name: produtos-ms-mongo
        image: mongo
        imagePullPolicy: IfNotPresent
        workingDir: /application
        #imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: produtos-ms-mongo
          mountPath: /application
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always