apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtos-ms
  namespace: produtos-ms
  labels:
    app: produtos-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtos-ms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: produtos-ms
    spec:
      containers:
      - name: produtos-ms
        envFrom:
        - configMapRef:
       # - secretRef:
            name: produtos-ms-configmap
        image: adrianoelima/produtos-ms:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        workingDir: /var/www
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /tmp
          type: Directory
        name: tmpdir
