version: "3.1"
services:
  produtos-ms-mongo:
      build:
        context: .
        dockerfile: docker/database/Dockerfile
      container_name: produtos-ms-mongo
      volumes:
        - ./docker/database/postgres:/application/
      environment:
        - MONGO_INITDB_ROOT_USERNAME=totem
        - MONGO_INITDB_ROOT_PASSWORD=totem
      ports:
        - "27017:27017"
      networks:
        - default

  produtos-ms:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: produtos-ms
    volumes:
      - ./docker/bin:/var/bin
    command: sh -c "npm install && chown -R www-data:www-data /var/www"
    ports:
      - "3000:3000"
    links:
      -   produtos-ms-mongo
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
volumes:
  dbdata:
    driver: local